### ISSUE TITLE
Team Essentials page: Update diagram image with latest in box

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/ai-design#1]
The current diagram is off gird, but now i fixed it. current image in box

<img width="885" alt="Screen Shot 2019-06-07 at 1 45 11 PM" src="https://user-images.githubusercontent.com/46679352/59205088-b240e300-8b67-11e9-9dc1-6af6c95ffef0.png">

**Comment by lawhump** [comment]
<img width="1185" alt="Screen Shot 2019-10-15 at 11 06 19 AM" src="https://user-images.githubusercontent.com/5386917/66849059-dbb9b300-ef3b-11e9-80e4-e893f31c2953.png">
