### ISSUE TITLE
The user gets redirected to in some circumstances

### ISSUE THREAD

**Issue by rodet** [IBM-Design/ai-design#11]
This morning I was surprised by the URL in my browser, which was http://ai-design.eu-de.mybluemix.net/design/ai/ . I had some page of the website open for a couple days already.

Steps to reproduce:
1. Go to a subpage like https://www.ibm.com/design/ai/conversation/ but not https://www.ibm.com/design/ai/
2. Hit "Reload this page" in Chrome or Firefox. You will now see a different host and URL, like http://ai-design.eu-de.mybluemix.net/design/ai/conversation/ . This won't happen on the main page https://www.ibm.com/design/ai/ .

Notice the protocol is then switching from HTTPS to HTTP.

This problem happens on manual refreshes, but I think I also got it by restarting my machine or restarting the browser and then choosing the restore the former session.

**Comment by lawhump** [comment]
This is a known issue with everything off of /design. I don't know the root why, but an intermediate fix depends on the absence or presence of the trailing slash.

ibm.com/design/ai/fundamentals
vs
ibm.com/design/ai/fundamentals/

Hopefully you know why it's doing this :)

**Comment by rodet** [comment]
My impression is that this redirect comes from the nginx configuration. At least it would be good to have a look at it. Let's talk this on Slack later today.

**Comment by lawhump** [comment]
It was an nginx issue, fixed now.
