### ISSUE TITLE
"Overview" always in selected state

### ISSUE THREAD

**Issue by shixiedesign** [IBM-Design/ai-design#12]
### "Overview" under the left nav doesn't deselect

![image](https://user-images.githubusercontent.com/15144993/63046452-1188df80-be98-11e9-88c6-dc3655f33ac1.png)

![image](https://user-images.githubusercontent.com/15144993/63046512-30877180-be98-11e9-8140-df7752ffe549.png)

**Comment by lawhump** [comment]
Fixed in the Gatsby update
