### ISSUE TITLE
Move Body copy on landing page on grid

### ISSUE THREAD

**Issue by RyanCaruthers** [IBM-Design/ai-design#2]
currently it is still off grid, see attached. Maybe see if Vince can help.

<img width="1088" alt="Screen Shot 2019-06-07 at 9 50 59 AM" src="https://user-images.githubusercontent.com/46679352/59205228-16fc3d80-8b68-11e9-82b7-c68580c971c3.png">
<img width="1041" alt="Screen Shot 2019-06-07 at 9 52 56 AM" src="https://user-images.githubusercontent.com/46679352/59205229-16fc3d80-8b68-11e9-8278-866b654072e3.png">

**Comment by lawhump** [comment]
Fixed between https://github.com/IBM-Design/ai-design/commit/d284044eac61ac442cce0f38f51e0bb2a0b51fff and https://github.com/IBM-Design/ai-design/commit/6eba6cf601dba11692007bd1d2f3e1ae7e40440a
